/**
 * Display pages for the formats this app may not ship a runtime for.
 *
 * Live2D's Cubism Core is proprietary and Spine's runtime needs a licence
 * from Esoteric — neither can go in the installer. But *not shipping a
 * runtime* is not the same as *not supporting the format*: the app can
 * write a self-contained page that loads a runtime out of the model's own
 * `runtime/` folder, and then simply display that page.
 *
 * So the bypass is: the user brings the runtime (which they are entitled to
 * do), the app brings the page, and the overlay shows the result. Nothing
 * proprietary is redistributed and nothing is downloaded behind the user's
 * back.
 *
 * The generated page is written to be honest on its own: if the runtime
 * files are not there, it says which ones, instead of showing a blank
 * rectangle.
 */
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { REQUIRED_RUNTIME } from './avatars';

const findFile = (dir: string, pattern: RegExp): string | null => {
  const walk = (at: string, depth: number): string | null => {
    for (const entry of readdirSync(at, { withFileTypes: true })) {
      const full = join(at, entry.name);
      if (entry.isDirectory()) {
        if (depth <= 0) continue;
        const found = walk(full, depth - 1);
        if (found) return found;
        continue;
      }
      if (pattern.test(entry.name)) return full;
    }
    return null;
  };
  return walk(dir, 3);
};

/** relative path from the folder root, forward slashes, URL-encoded */
const rel = (dir: string, file: string): string =>
  file.slice(dir.length + 1).split(/[\\/]/).map(encodeURIComponent).join('/');

const GUARD = (required: string[]): string => `
    const REQUIRED = ${JSON.stringify(required)};
    async function present(name) {
      try { const r = await fetch('runtime/' + name, { method: 'GET' }); return r.ok; }
      catch { return false; }
    }
    async function loadRuntime() {
      const missing = [];
      for (const name of REQUIRED) if (!(await present(name))) missing.push(name);
      if (missing.length) { explain(missing); return false; }
      for (const name of REQUIRED) {
        await new Promise((resolve, reject) => {
          const el = name.endsWith('.css')
            ? Object.assign(document.createElement('link'), { rel: 'stylesheet', href: 'runtime/' + name })
            : Object.assign(document.createElement('script'), { src: 'runtime/' + name });
          el.onload = resolve; el.onerror = () => reject(new Error(name));
          document.head.appendChild(el);
        });
      }
      return true;
    }
    function explain(missing) {
      document.body.innerHTML =
        '<div class="note"><b>런타임 파일이 필요합니다</b>'
        + '<p>이 포맷의 런타임은 자유롭게 재배포할 수 없어 앱에 동봉되지 않습니다.'
        + ' 아래 파일을 이 모델 폴더의 <code>runtime/</code> 안에 넣어 주세요.</p>'
        + '<ul>' + missing.map((m) => '<li><code>' + m + '</code></li>').join('') + '</ul>'
        + '<p class="dim">' + HINT + '</p></div>';
    }
    function fail(err) {
      document.body.innerHTML = '<div class="note"><b>표시할 수 없습니다</b><p>' + String(err && err.message || err) + '</p></div>';
      post({ loaded: false, error: String(err && err.message || err) });
    }
    function post(status) {
      window.__genyEmbed = status;
      try { window.parent.postMessage({ genyStatus: status }, '*'); } catch (e) {}
    }`;

/** Shared by the Live2D page: measure what was drawn and report it up. */
const REPORT = `
    function report(model, app) {
      var visible = null;
      try {
        var px = app.renderer.extract.pixels(model);
        visible = 0;
        for (var i = 3; i < px.length; i += 4) if (px[i] > 8) visible++;
      } catch (e) { /* extract is best-effort; loaded still means loaded */ }
      post({
        loaded: true,
        width: Math.round(model.width),
        height: Math.round(model.height),
        visiblePixels: visible,
      });
    }`;

const STYLE = `
    html, body { margin: 0; height: 100%; background: transparent; overflow: hidden;
      font: 13px/1.5 ui-sans-serif, system-ui, 'Noto Sans KR', sans-serif; color: #e7ecf3; }
    canvas, #stage { width: 100%; height: 100%; display: block; }
    .note { margin: 10px; padding: 10px 12px; border-radius: 8px; background: rgba(0,0,0,.72); }
    .note code { color: #a99bff; } .note ul { margin: 6px 0 0 16px; padding: 0; }
    .dim { color: #8b97a8; font-size: 11px; }`;

function live2dPage(dir: string): string {
  const model = findFile(dir, /\.model3\.json$/i);
  if (!model) throw new Error('이 폴더에 .model3.json 이 없습니다');
  return `<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><title>Live2D</title><style>${STYLE}</style></head>
<body><script>
    // Generated by Geny. Edit freely — the app will not overwrite it.
    const MODEL = ${JSON.stringify(rel(dir, model))};
    const HINT = 'pixi.min.js 와 pixi-live2d-display.min.js 는 앱이 넣어 줍니다(MIT). '
      + 'live2dcubismcore.min.js 는 [설정 → 아바타]의 [Cubism Core 받기] 로 Live2D 공식 '
      + '배포처에서 이 폴더로 내려받으세요.';
    var mouth = 0, mouthHooked = false;
${GUARD(REQUIRED_RUNTIME.live2d)}
${REPORT}
    (async () => {
      try {
        if (!(await loadRuntime())) return;
        const app = new PIXI.Application({
          view: Object.assign(document.body.appendChild(document.createElement('canvas')), { id: 'stage' }),
          resizeTo: window, backgroundAlpha: 0, antialias: true,
        });
        const model = await PIXI.live2d.Live2DModel.from(MODEL);
        app.stage.addChild(model);
        const fit = () => {
          const scale = Math.min(window.innerWidth / model.width, window.innerHeight / model.height);
          model.scale.set(scale);
          model.x = (window.innerWidth - model.width) / 2;
          model.y = window.innerHeight - model.height;
        };
        fit(); window.addEventListener('resize', fit);

        // Tell the app what actually happened. The pixel count comes from
        // pixi's extract, which re-renders into a texture — reading the
        // canvas directly always returns zeros, because the drawing buffer
        // is cleared after compositing (preserveDrawingBuffer is false).
        report(model, app);
        // The app tells the page what the agent is doing and how loud the
        // synthesized speech currently is. A model with matching expressions
        // reacts; one without simply will not.
        window.addEventListener('message', (e) => {
          const d = e.data || {};
          if (d.genyMood && model.expression) { try { model.expression(d.genyMood); } catch (err) {} }
          if (typeof d.genyMouth === 'number' && model.internalModel) {
            try {
              // set every frame, because the model's own motion writes this
              // parameter too and would otherwise overwrite ours
              var core = model.internalModel.coreModel;
              mouth = d.genyMouth;
              if (!mouthHooked) {
                mouthHooked = true;
                model.internalModel.motionManager.on('*', function () {});
                app.ticker.add(function () {
                  try { core.setParameterValueById('ParamMouthOpenY', mouth); } catch (err) {}
                });
              }
            } catch (err) {}
          }
        });
      } catch (err) { fail(err); }
    })();
</script></body></html>
`;
}

function spinePage(dir: string): string {
  const atlas = findFile(dir, /\.atlas(\.txt)?$/i);
  if (!atlas) throw new Error('이 폴더에 .atlas 가 없습니다');
  const skeleton =
    findFile(dir, /\.skel(\.bytes)?$/i) ??
    findFile(dir, new RegExp(`^${basename(atlas).replace(/\.atlas(\.txt)?$/i, '')}\\.json$`, 'i')) ??
    findFile(dir, /\.json$/i);
  if (!skeleton) throw new Error('이 폴더에 스켈레톤(.skel 또는 .json)이 없습니다');
  const binary = /\.skel(\.bytes)?$/i.test(skeleton);
  return `<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><title>Spine</title><style>${STYLE}</style></head>
<body><div id="stage"></div><script>
    // Generated by Geny. Edit freely — the app will not overwrite it.
    const ATLAS = ${JSON.stringify(rel(dir, atlas))};
    const SKEL = ${JSON.stringify(rel(dir, skeleton))};
    const BINARY = ${binary};
    const HINT = 'spine-player.js 와 spine-player.css 는 Esoteric Software 의 Spine Web Player 배포본에 '
      + '들어 있습니다. 사용에는 Spine 라이선스가 필요합니다.';
${GUARD(REQUIRED_RUNTIME.spine)}
    (async () => {
      try {
        if (!(await loadRuntime())) return;
        const player = new spine.SpinePlayer('stage', {
          atlasUrl: ATLAS,
          ...(BINARY ? { skelUrl: SKEL } : { jsonUrl: SKEL }),
          backgroundColor: '#00000000', alpha: true,
          showControls: false, premultipliedAlpha: true,
          error: (_p, msg) => fail(new Error(msg)),
        });
        window.addEventListener('message', (e) => {
          const mood = e.data && e.data.genyMood;
          if (!mood || !player.animationState) return;
          try { player.setAnimation(mood, true); } catch {}
        });
      } catch (err) { fail(err); }
    })();
</script></body></html>
`;
}

const README = (kind: 'live2d' | 'spine'): string => {
  if (kind === 'live2d') {
    return `이 폴더는 Live2D 모델로 인식됐고, 표시용 페이지(index.html)가 만들어졌습니다.

앱이 넣어 준 것 (MIT — 재배포 가능해서 설치 파일에 들어 있습니다)
  runtime/pixi.min.js
  runtime/pixi-live2d-display.min.js

남은 하나
  runtime/live2dcubismcore.min.js

이것만 앱에 동봉되어 있지 않습니다. 파일 자체는 Live2D 가 "Redistributable Code"
로 지정한 것이지만, 이 앱처럼 사용자가 모델을 무제한으로 넣는 아바타 시스템은
Live2D 가 "Expandable Application" 으로 분류해 개인·소규모 면제 대상에서 제외하고
별도 계약을 요구합니다. 그래서 앱이 배포하는 대신, [설정 → 아바타]의
[Cubism Core 받기] 버튼이 Live2D 공식 배포처에서 이 폴더로 직접 내려받습니다.

  https://help.live2d.com/en/sdk/sdk_001/

index.html 은 앱이 덮어쓰지 않으니 자유롭게 고쳐도 됩니다.
`;
  }
  return `이 폴더를 아바타로 표시하려면 런타임 파일이 필요합니다.

Spine 런타임은 Esoteric Software 의 라이선스가 필요해 앱에 동봉할 수 없습니다.
앱은 표시용 페이지(index.html)를 만들어 두었고, 그 페이지는 아래 파일들을
이 폴더의 runtime/ 에서 찾아 불러옵니다.

필요한 파일
  runtime/spine-player.js
  runtime/spine-player.css

Spine Web Player 배포본에 들어 있습니다. 사용에는 Spine 라이선스가 필요합니다.

넣고 나서 앱의 [설정 → 아바타]에서 [다시 찾기]를 누르면 바로 표시됩니다.
index.html 은 앱이 덮어쓰지 않으니 자유롭게 고쳐도 됩니다.
`;
};

/**
 * Write the display page (and a note about what is still needed).
 *
 * Never overwrites an existing `index.html`: once the user has a page,
 * theirs is the authority on how their avatar looks.
 */
export function scaffold(
  dir: string,
  kind: 'live2d' | 'spine',
  /** Live2D only: copies the MIT half of the runtime in, so the user is left
   *  needing exactly one file instead of three */
  installRuntime?: (modelDir: string) => string[],
): { page: string; created: boolean; installed: string[] } {
  const page = join(dir, 'index.html');
  const installed = kind === 'live2d' && installRuntime ? installRuntime(dir) : [];
  if (existsSync(page)) return { page, created: false, installed };
  writeFileSync(page, kind === 'live2d' ? live2dPage(dir) : spinePage(dir), 'utf8');
  mkdirSync(join(dir, 'runtime'), { recursive: true });
  writeFileSync(join(dir, 'runtime', 'README.txt'), README(kind), 'utf8');
  return { page, created: true, installed };
}
